name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: download
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          chmod +x ./bin/yt-dlp
          ./bin/yt-dlp --config-locations config.txt
          git add .
          git commit -m "download youtube video"
          git push
